const routes = require('next-routes')

module.exports = routes()
.add('dashboard', '/dashboard')
.add('newUser', '/nuevo-alta')
.add('editUser', '/editar-perfil/:id')
.add('typography', '/typography')
.add('icons', '/icons')
.add('maps', '/maps')
.add('notification', '/notification')